### ISSUE TITLE
Current CRS versions not visible on front page

### ISSUE THREAD

**Issue by dune73** [coreruleset/website#29]

**Comment by fzipi** [comment]
Don't know what you expect here. I've added a variable so we can refer to the latest version now in #36.

**Comment by dune73** [comment]
Ideally, I would like to see 4.1.0 and 3.3.5 on the first screen of the website somewhere without having to scroll.

**Comment by fzipi** [comment]
Added #43

**Comment by fzipi** [comment]
Done.
