### ISSUE TITLE
Remaining tasks for migrating from production

### ISSUE THREAD

**Issue by fzipi** [coreruleset/website#32]
These are the tasks we should do before moving to production:
- [x] update with new blogposts from prod
- [x] confirm that Alessandro has access and can update the website
- [x] add a step to check broken links in the website (#31)
- [x] review the content is showing properly (this should be incremental) (partially in #31 with links to images fixed)
- [x] create a new CNAME file with the `coreruleset.org`
- [x] point the DNS name to the new resource (review security settings and implications)

**Comment by fzipi** [comment]
Migration done. Still some links hiccups, but mostly working.

**Comment by dune73** [comment]
Very good job. And we'll get the links sorted out. Thank you.
