### ISSUE TITLE
Home button leads to 404 error

### ISSUE THREAD

**Issue by EsadCetiner** [coreruleset/website#33]
The home button at https://coreruleset.github.io/website/ points to / which leads to a 404 error, it should be pointing to /website/ to avoid the 404 error.

https://github.com/coreruleset/website/assets/104706115/f90fff4d-4375-4eed-895a-db7eb9722893

**Comment by dune73** [comment]
This is because the dev-installation is in a subfolder. But once this runs on https://coreruleset.org, pointing to "/" is the right behavior.

At least this, is what I think.

**Comment by EsadCetiner** [comment]
closing since the issue is fixed in production.
