### ISSUE TITLE
RSS feed is broken

### ISSUE THREAD

**Issue by woefe** [coreruleset/website#49]
Congrats on the new website! :rocket: 

I was following the blog through the RSS feed. I found the new feed at https://coreruleset.org/blog/index.xml. The feed is currently broken. After some digging, I found the issue in the upstream theme and created https://github.com/cncf/dot-org-hugo-theme/pull/46

Please pull in the latest theme once the PR is merged :heart:

**Comment by fzipi** [comment]
We can use that fix locally and then use upstream when merged also.

**Comment by fzipi** [comment]
Sorry, should be fixed now, thanks to your patch!
