### ISSUE TITLE
Move blog files to subdirectories

### ISSUE THREAD

**Issue by fzipi** [coreruleset/website#58]
After dumping blog posts from Wordpress, we ended up with a one level hierarchy that is not easy to maintain and too long to read.

Proposal: create subdirectories per topic, or similar, so we can store releated files together.

If we agree on this, then we need to think about the directories we use. An example:

```
portraits
releases
news
reports
...
```

Note: urls on blog posts will remain the same.

**Comment by fzipi** [comment]
@dune73 What do you think?

**Comment by dune73** [comment]
The posts are prefixed by date. So easy to sort. They also come with multiple tags, so easy to filter in multiple dimensions.

I do not see the problem with the flat hierarchy, but I expect us to meet edge cases where it's not clear which would be the appropriate folder (news? reports?).

Unless you think we really, really need to move away from this, I'd rather keep it and remain flexible via the tags.

**Comment by fzipi** [comment]
🤷
