### ISSUE TITLE
Review sync between docs and main website

### ISSUE THREAD

**Issue by fzipi** [coreruleset/website#60]
Looks like the docs where updated (https://coreruleset.github.io/documentation/development/crs_toolchain/), but not the main website repo (https://coreruleset.org/docs/development/crs_toolchain/).

We need to review github workflow dispatch and runs.

**Comment by theseion** [comment]
Looks good to me. The website now shows the binary section first. Cache issue?

**Comment by fzipi** [comment]
Agreed. I can confirm the call form the repo dispatch was good: https://github.com/coreruleset/website/actions/runs/8849660122
