### ISSUE TITLE
Cross-posts from old blog site still broken

### ISSUE THREAD

**Issue by RedXanadu** [coreruleset/website#72]
Many (most? maybe _all_?) of the X-posts from the old blog site are now broken on the new website.

**Examples:**

(E.g. https://www.secjuice.com/web-application-firewall-waf-evasion/, https://owasp.blogspot.com/2017/12/core-rule-set-evolution-of-an-owasp-project.html)

1. Do we want to keep these cross posts?
2. If so, they need to be fixed.

A full list can be found on the old blog site (the IP address for this is in Slack somewhere…)

Thank you.

**Comment by fzipi** [comment]
Isn't this being addressed already by #71 ?
