### ISSUE TITLE
Incorrect image is displayed when sharing a post on Facebook

### ISSUE THREAD

**Issue by azurit** [coreruleset/website#79]
When sharing any link on Facebook (and probably on other social networks), this image is displayed in a preview:
https://coreruleset.org/img/social-share.png

The current image is not related to CRS at all and needs to be replaced, for example, with a logo (maybe https://coreruleset.org/images/logo/horizontal.svg ).

Here are requirements for a preview image for Facebook:
https://developers.facebook.com/docs/sharing/webmasters/images/

**Comment by fzipi** [comment]
Update the image with the logo in 5ae606c. Let's see how it renders.

**Comment by azurit** [comment]
@fzipi Can't see a new image anywhere.

**Comment by fzipi** [comment]
Fix was merged.

**Comment by azurit** [comment]
Fixed.

**Comment by dune73** [comment]
Thank you for taking the time to fix this @fzipi. I know how tedious things like this can be.
